language: node_js
sudo: required

services:
  - docker

env:
  - RENDERER_ACCESS_KEY=secret
  - CONCURRENCY=1
  - WINDOW_WIDTH=1024 WINDOW_HEIGHT=768
  - NODE_ENV=production
  - ELECTRON_ENABLE_STACK_DUMPING=true
  - ELECTRON_ENABLE_LOGGING=true

node_js:
  - "5.10"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - npm run lint
  - docker build --rm=true --force-rm=true -t msokk/electron-render-service .
  - npm test
